### ISSUE TITLE
Транспорт OCSP/TSA/DVCS

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#10]
В разделе 10 описывается транспорт для нестандартных процессов, введенных в разделе 9.  Но транспорт стандартных процессов взаимодействия с серверами OCSP/TSA/DVCS не определен. А между тем соответствующие стандарты (кроме СТБ 34.101.26-OCSP?) предлагают несколько вариантов транспорта.

Необходимо зафиксировать конкретные варианты транспорта сообщений OCSP/TSA/DVCS.

**Comment by agievich** [comment]
Цитата из CommonPKI относительно транспорта OCSP:

> There is no specific transport protocol specified in RFCs for OCSP. Similarly, there is no
dedicated “well-known” port reserved for OCSP. Common PKI compliant systems MUST
employ the Hypertext Transfer Protocol (HTTP) [RFC2616] to transport OCSP messages
between clients and a server. If no port number is provided in the corresponding URL, the
commonly used port No. 80 MUST be used. Using HTTP has the advantage that software
components are easy to implement and that transport over firewalls and proxies usually does
not require any special configuration. It is furthermore possible to provide for secure
transmission using Transport Layer Security (TLS) or Secure Socket Layer (SSL). Note that
since all relevant OCSP messages are signed and carry only public information, it is not
indeed necessary to provide for such additional security.

>An OCSP request will be sent to the responder by means of the POST method. The request
message MUST include the following lines:

```
POST` <responder URL>
...
Content-Type: application/ocsp-request
Content-Length: ...
<the DER-encoded OCSPRequest object >
...
```
>If the POST-request could be processed, the server MUST return response status 200 (OK)
and MUST include the DER-encoding of the resulting OCSPResponse object in the response
message. No transport encoding (e.g. to base-64 encoding) is to be applied, i.e. messages are
to be transported in unaltered, pure binary form.

**Comment by olegotory** [comment]
В стандаре на TSA (СШВ) описан "Обмен сообщениями с использованием протокола HTTP". В bpki для tsa можно сказать, что для США должен поддерживаться обмен сообщениями с использованием протокола HTTP, описанный в п. 8.4 СТБ 34.101.ts

**Comment by agievich** [comment]
Раздел "Транспорт" говорит теперь и об OCSP, TSA и DVCS.
