### ISSUE TITLE
Нонсы в штампах времени

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#11]
В запросы и ответы СШВ (службы штампов времени) запрещено включать нонсы -- неповторяющиеся синхропосылки, связывающие запрос с ответом. 

Несмотря на рекомендации RFC 3161, большого смысла в нонсах мы не видим. Поэтому нонсы и были заблокированы в BPKI. С другой стороны, на сегодняшний день сложилась практика поддержки нонсов "по желанию": клиент может указать нонс, а СШВ должен уметь его обработать. В частности, эта практика отражена в европейском профиле [ETSI EN 319 422](http://www.etsi.org/deliver/etsi_en/319400_319499/319422/01.01.00_30/en_319422v010100v.pdf).

С учетом сложившейся практики предлагается разрешить нонсы в BPKI. Рекомендовать использовать нонсы из 8 октетов.

**Comment by olegotory** [comment]
Поддерживаю предложение относительно включения компонента nonce "по желанию".

Небольшой коментарий по поводу nonce.
В СТБ 34.101.ts сказано, что nonce является необязательным компонентом, который определяет значение, используемое для проверки своевременности ответа в случае отсутствия у отправителя запроса локального источника времени. В СТБ 34.101.ts также сказано, что компонент nonce РЕКОМЕНДУЕТСЯ включать в запрос. 
Основная нагрузка по поддержке nonce ложится на отправителя запроса (генерация, включение в запрос), от СШВ требуется только перенести nonce из запроса в ответ. Отправитель запроса может сам решать, нужно ли ему отслеживать связь запроса и ответа. Отметим, что запрос никак не идентифицирует отправителя. Рассмотрим несколько случаев, когда nonce нужна для связывания запроса и ответа:
1) одним отправителем передано несколько запросов на одни и те же данные (т.е. на данные, у которых совпадает хэш-значение);
2) несколькими отправителями переданы запросы на одни и те же данные.
В случае отсутствия nonce и если отправитель не отслеживает своевременность ответа у злоумышленника есть возможность поменять ответы для запросов.

**Comment by pavlovkv** [comment]
Я так понимаю, что я в меньшинстве, но все же я против включения nonce.  Изначально было желание облегчить все форматы, в том числе и штамп времени. Я не вижу особой надобности во включении данного компонента. На мой взгляд он ничем не отличается от ряда других компонентов, которые мы не включаем в шв. Рассмотрим подробнее ситуации 1 и 2 из предыдущего комментария:
1. Пользователь получит два штампа времени на одни и те же данные (хотя странно, что ему это вообще может понадобиться). Он вправе выбрать штамп времени, в котором значение компонента gentime меньше. Штамп времени ставится на данные, а не на запрос. И для всех запросов поступающих
2. Даже если противник поменяет местами ответы, шв от этого не станет недействительным. В чем здесь опасность? Ведь неважно кто и когда отправил запрос, важен сам штамп времени. А если все же важно, то злоумышленник может угнать запрос, и сказать, что он сформировал этот запрос, ведь запрос не подписывается и доказать его связь с определенным пользователем невозможно.

**Comment by agievich** [comment]
Нонсы используются в запросах / ответах OCSP, СЗД (DVCS), СШВ (TSA), а также в BPKIRetrieveReq / BPKIResp. Только в последнем случае использование нонсов жестко регламентировано. В первых трех -- по желанию. Более того, в OCSP формат нонсов вообще не определен (по крайней мере, в СТБ 34.101.26).

При ближайшем рассмотрении я не вижу смысла в нонсах OCSP, СЗД, СШВ. Рассмотрим, например, штамп времени. Это доказательство существования некоторых данных к некоторому моменту времени. Доказательство _объективное_, не зависящее от того, кто его запросил у СШВ. А нонс -- это механизм связывания доказательства с запрашивающей стороной. Непонятно, как может пригодиться такое связывание.

**Comment by olegotory** [comment]
Рассмотрим один пример, где по моему мнению связывание важно.
Предположим есть электронная биржа, в которой стороны, что-то покупающие, подписывают свои заявки с использованием штампов времени. Если две стороны предложили одну цену, то товар отходит сторонке, подписавшей заявку первой. Как доказать с использованием только запросов и штампов времени, что кто-то получил штамп первым? Я не вижу решения без использования nonce. Наверное можно найти и другие примеры, где nonce важно. Зачем нам убирать эту возможность7

**Comment by pavlovkv** [comment]
Представим, что в случае с биржей Алиса и Виктор предъявляют свой штампы времен для выявления победителя. Виктор получил ШВ позже, поэтому "угоняет" штамп времени Алисы, чтобы хоть как-то попытаться побороться за победу в торгах. Но как здесь поможет нонс? Какая разница "угонять" ШВ с нонсом или без?  Нонс -- не подпись и  не доказывает, что кто-то создал запрос. Если я правильно все понял, то нонс не спасает в данной ситуации. 
 
Остаюсь при своем мнении.

**Comment by agievich** [comment]
Без нонсов.
