### ISSUE TITLE
Подписанные атрибуты в штампе времени

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#12]
Штамп времени представляет собой контейнер SignedData, в который инкапсулирована структура TSTInfo. При инкапсуляции структуре назначается идентификатор id-ct-TSTInfo. Поскольку этот идентификатор отличается от стандартного (id-data), по правилам СТБ 34.101.23 (cms) контейнер SignedData должен содержать по крайней мере 2 подписанных атрибута: contentType и messageDigest. 

Однако в BPKI **ошибочно сказано**, что штамп времени не содержит подписанных атрибутов.

**Comment by pavlovkv** [comment]
Да, это действительно так.

**Comment by agievich** [comment]
Текст по SignedData будет усилен (с учетом #21).
