### ISSUE TITLE
SigningCertificate vs SigningCertificateV2

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#13]
Тема #12 о подписанных атрибутах в штампах времени не закрыта.

СТБ 34.101.ts **требует включения** в штамп еще одного атрибута: SigningCertificateV2. Этот атрибут описывает хэш-значение сертификата СШВ, а также опционально пару "издатель сертификата, серийный номер". Эта пара уже присутствует в SignerInfo штампа времени, поэтому ее нужно обязательно подавить в SigningCertificateV2.

Но и это еще не все. Как следует из названия, атрибут SigningCertificateV2 является новой версией атрибута SigningCertificate. В старом атрибуте сертификат может хэшироваться только с помощью SHA-1, в новом атрибуте -- с помощью любого хэш-алгоритма. Несмотря на введение SigningCertificateV2, существующие системы продолжают использовать SigningCertificate. В европейском профиле [ETSI EN 319 422](http://www.etsi.org/deliver/etsi_en/319400_319499/319422/01.01.00_30/en_319422v010100v.pdf) разрешается использовать и SigningCertificate, и SigningCertificateV2.

В СТБ 34.101.tsp было принято решение заблокировать SigningCertificate. Считаю это решение ошибочным. Атрибут не имеет никакого значения (однозначная информация о сертификате подписанта указывается в SignerInfo), является атавизмом, нужным только для совместимости и следованию канону. 

В целом предлагаю:
1. Разрешить в СТБ 34.101.ts оба атрибута: SigningCertificate и SigningCertificateV2. Возможно потребуется внести изменение еще и в СТБ 34.101.ades.
2. В BPKI также разрешить оба атрибута.
3. В BPKI заблокировать поле IssueSerial атрибутов.

Использование SHA-1 в SigningCertificate не должно смущать, ведь SHA-1 уже разрешается использовать в расширениях SKID / AKID сертификата.

**Comment by olegotory** [comment]
Действительно, в обновлении для RFC 3161, который лег в основу СТБ 34.101.ts, разрешается использовать как атрибут SigningCertificate, так и атрибут SigningCertificateV2 (см. RFC 5816). При разработке СТБ 34.101.ts было принято решение отказаться от атрибута SigningCertificate, для которого сертификат может хэшироваться только алгоритмом SHA-1. Возможно данное решение было ошибочным и не учитывало существующую практику, требования совместимости.

Предложения поддерживаю. Следует определиться где описывать атрибут SigningCertificate: в СТБ 34.101.ts или СТБ 34.101.ades. Мое мнение, что более уместно его описать в СТБ 34.101.ades, как сделано для атрибута SigningCertificateV2.

**Comment by pavlovkv** [comment]
Очень интересен вот этот момент: 

> СТБ 34.101.ts требует включения в штамп еще одного атрибута: SigningCertificateV2.

Я эту фразу понимал, как если сертификат включается, то  следует таким-то правилам. Если это не так, чем обусловлена такая обязательность? Я думал, что сертификат включается только в том случае, если указан certReq = true. Вот, например, цитата из RFC 3161:

> If the certReq field is missing or if the certReq field is present
>    and set to false then the certificates field from the SignedData
>    structure MUST not be present in the response.

**Comment by olegotory** [comment]
Атрибут SigningCertificateV2 не содержит сертификат. Он содержит хэш-значение сертификата, серийный номер сертификата и имя издателя сертификата. Данная информация требуется для поиска сертификата стороны, которая подписала штамп времени.

**Comment by agievich** [comment]
В п. 8.9.2 добавлен текст:
> Контейнер `SignedData` должен содержать ссылку на сертификат СШВ в виде подписанного атрибута `SigningCertificate` или `SigningCertificateV2`. Атрибуты определены в СТБ 34.101.80. Во вложенных в `SigningCertificate` контейнерах `CertID` должны опускаться компоненты `issueAndSerialNumber`. В атрибуте `SigningCertificateV2` должен быть опущен компонент `policy`, а во вложенных контейнерах `ESSCertIDv2` должны опускаться компоненты `issueAndSerial1.

Не закрываю issue, чтобы не забыть:
- [ ] добавить описание `SigningCertificate` в СТБ 34.101.ades;
- [ ] добавить разрешение на использование `SigningCertificate` в СТБ 34.101.tsp.

**Comment by semenov-vladyslav** [comment]
Исправил описание атрибута `SigningCertificate` в [CAdES](https://bitbucket.org/bcrypto/ades/commits/4fb4c520f95a02b80ae4adbb4e12bd1a2272287e):
атрибут остается один, но для его представления в CAdES могут использоваться типы АСН.1 `SigningCertificate` или `SigningCertificateV2` в зависимости от хэш-функции.

**Comment by agievich** [comment]
Перенес СТБ 34.101.80 (ADES) в репозиторий https://github.com/bcrypto/stb. Теперь работу с ADES следует вести через этот репозиторий. 

Есть замечание по описанию атрибута `SigningCertificate` в ADES: странная фраза 

> ... атрибут предназначен для предотвращения простых атак с подменой и повторной выдачей сертификата...

Нужно перефразировать или объяснить.

**Comment by agievich** [comment]
Закрывается. Перебросил последнее замечание в https://github.com/bcrypto/stb/issues/1.
