### ISSUE TITLE
Запрос сертификата СШВ

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#14]
В запросе на выпуск штампа времени запрещено устанавливать certReq = TRUE. Таким образом, клиент не может попросить СШВ вложить сертификат в штамп времени. Считаю такую ситуацию неправильной. Клиент **должен иметь возможность запросить** у СШВ его сертификат.

**Comment by pavlovkv** [comment]
Не вижу в этом особой необходимости. Считаю, что сертификат СШВ должен быть доступен на портале его владельца. Поскольку республиканская СШВ будет одна, контролировать актуальность сертификата СШВ не составит особого труда. Если не ошибаюсь, например, у испанцев сертификат СШВ  доступен на сайте.

**Comment by olegotory** [comment]
Даже если служба одна, у нее может быть несколько личных ключей и, соответственно, сертификатов (для ускорения обработки запросов, например). Поэтому согласен, что клиент должен иметь возможность запросить у СШВ его сертификат (для автоматизации проверки), иначе придется проверку осуществлять перебором.

**Comment by agievich** [comment]
Дано разрешение на запрос. См. #16.
