### ISSUE TITLE
Accuracy в штампе времени

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#15]
В штампе времени подавлено поле `accuracy`, в котором описывается "разрешающая способность" (РС) таймера СШВ. При отсутствии в штампе клиенты могут получить РС только из описания политики СШВ. Идентификатор политики объявлен в BPKI и здесь же следует сказать про РС. 

Есть два варианта:
1. Заявить РС в BPKI и не вводить `accuracy` в штамп времени.
2. Требовать наличия `accuracy` в штампе времени. Одновременно ввести в BPKI верхнюю границу для PC (например, одна секунда).

Я сторонник второго варианта.

**Comment by olegotory** [comment]
Поддерживаю второй вариант.
В том же европейском профиле ETSI EN 319 422 включение компонента accuracy требуется: "the accuracy field shall be supported". Считаю, что в стандарте не следует определять верхнюю границу, а задавать верхнюю границу в политике СШВ. В частности мы не знаем, сможет ли НЦЭУ поддержать точность до 1 сек.? Возможно со временм точность будет увеливаться. При необходимости политику поменять не сотавляет большого труда, внести же изменения в стандарт требует значительно больше усилий.

**Comment by pavlovkv** [comment]
То же мнение, что и по поводу nonce: зачем утяжелять штамп времени? Какую практическую пользу принесет включение этого компонента? Зачем пользователю знать вообще точность из ответа? В каких случаях точность может критически повлиять на результат, если она будет в ответе, а не в политике?
Поэтому я предлагаю третий вариант: РС заявляется только в политике. Политику корректирует владелец СШВ, поскольку заведомо мы не можем знать какие условия смогут обеспечить для данного СШВ. Реалии всегда отличаются от теории.

**Comment by agievich** [comment]
Политика (документ) не автоматизируется. Агент / бот / автомат не сможет понять, что написано в политике. Но он сможет разобрать поле `accuracy`.

Разрешающая способность таймера может быть критически важна в real-time системах.

**Comment by pavlovkv** [comment]
Остаюсь при своем мнении: не вижу необходимости включать РС в ШВ. Не совсем ясны выгоды от данного действия.

**Comment by agievich** [comment]
Компромиссное решение:
1. Компонент `accuracy` включается опционально.
2. Требования по РС (разрешающей способности) в `accuracy` не выдвигаются.
