### ISSUE TITLE
Атрибут streetAddress

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#17]
Атрибут `streetAddress` не упоминается в качестве обязательного в стандартах PKIX (напомню, что СТБ 34.101.19 является переводом RFC 3280, подготовленного [PKIX](https://datatracker.ietf.org/wg/pkix/about/)). Например, в СТБ 34.101.19 не задана максимальная длина `streetAddress`, мы взяли ее из X.520, где собственно атрибут и описан.

Атрибут `streetAddress` слабо канонизируется: нужно очень много подробностей, чтобы описать однозначный формат адреса. 

Предлагаю исключить атрибут.

При принятии решения об исключении того или иного id-атрибута мы находимся на развилке: id-атрибуты _однозначно идентифицируют_ субъекта или _рассказывают о нем_. Если "_однозначно идентифицируют_", то атрибутов должно быть немного. Подробности можно вынести в атрибутные сертификаты.

**Comment by olegotory** [comment]
Атрибут streetAddress содержит довольно таки чуствительную информацию -- адрес. Зачем кому-то знать, где точно физически (по какому точному адресу) располагается tls-сервер или КА. ЮП могут менять адреса, и как поступать, если у него адрес поменялся: формально сертификат должен отзываться, но кто это будет отслеживать, очень это сложно ...  При включении адреса также непонятно, почему не он не указывается на белорусском (как в паспорте). Адрес один из самых больших по размеру атрибутов. Поэтому думаю исключение данного атрибута пойдет только на пользу.

По атрибутам у меня есть вопрос: почему не все из них содержат информацию на белорусском языке?  Не будет ли с этим проблем?

**Comment by agievich** [comment]
Атрибут `streetAddress` исключен. Подробнее раскрыты типы населенных пунктов в `localityName`.
