### ISSUE TITLE
Максимальные длины name, surname, givenName

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#18]
В соответствии с СТБ 34.101.19 строки id-атрибутов `name`, `surname`, `givenName` могут содержать вплоть до 32768 символов. Верхняя граница весьма завышена. Из-за этого завышения нельзя построить разумные оценки максимальном объеме сертификата. 

Предлагается ввести жесткие ограничения на длины строк:
- длина `name` (полное название организации) <= 256.
- длина `surname` (фамилия на бел/рус) <= 128;
- длина `givenName` (имя + отчество на бел/рус) <= 256.

Хватит ли нам длин? М.б. на практике встречались не укладывающиеся в предлагаемые ограничения фамилии, имена, названия организаций?

**Comment by olegotory** [comment]
Если полное название организации указывать еще на белорусском языке, то данного размера недостаточно будет. Может сделать побольше  name?  <=512

**Comment by agievich** [comment]
Максимальные длины изменены (см. #31).
