### ISSUE TITLE
Канонизация id-атрибутов

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#19]
По правилам СТБ 34.101.19 (п. 9.1) при сравнении строк id-атрибутов должны игнорироваться незначащие пробелы и регистры символов (например, строки `"Иван Петров"` и `"ИВАН  ПетрОв "` считаются одинаковыми). Другими словами, перед сравнением строк должна проводиться их неявная канонизация: исключение незначащих пробелов, поднятие регистра.

> Кстати, строки атрибутов должны быть либо типа `PrintableString`, либо `UTF8String`. Это правило СТБ 34.101.19 в действующих сертификатах ГосСУОК не соблюдается.

В связи с неявной канонизацией мы запретили использовать строчные буквы в атрибутах `surname` и `givenName`. Можно пойти дальше и запретить строчные буквы и незначащие 
пробелы во всех основных id-атрибутах. Это упростит сравнение имен субъектов и эмитентов. С учетом жесткого порядка id-атрибутов (он также требуется в СТБ 34.101.19 [п. 9.2]) сравнивать можно будет просто DER-коды имен. Интересно, что в TLS-сервер в `CertificateRequest` указывает именно DER-коды имен доверенных УЦ.  

С другой стороны, явная канонизация id-атрибутов ухудшит их восприятие человеком. Явная канонизация не распространена в современных ИОК.

Развилка:
1. Без явной канонизации (так сейчас).
2. Явная канонизация (пробелы + регистр).
3. Явная канонизация наполовину: только незначащие пробелы.

**Comment by olegotory** [comment]
Учитывая, что основные продукты, используемые на практике (например, OpenSSL), не выполняют канонизацию, я за явную (позицию 2).

**Comment by agievich** [comment]
Тотальное поднятие регистра все-таки нецелесообразно (Представим себе "WWW.EXAMPLE.COM" в commonName TLS-сервера). Более того, название организации с поднятым регистром может не соответствовать удостоверению ЮЛ. 

С другой стороны, запретить незначащие пробелы целесообразно. Запрет добавлен в п. 7.3.1.
