### ISSUE TITLE
emailProtection в сертификатах

### ISSUE THREAD

**Issue by pavlovkv** [bcrypto/bpki#2]
**Проблема.** Надо ли указывать emailProtection для SignedData / EnvelopedData?
**Обсуждение.** Никаких веских оснований для этого нет.  Было предположение, что SignedData / EnvelopedData не будут работать в openssl. Но у меня получилось.  Как я понял, данный флаг используется если генерировать подпись в mime-формате.

**Comment by agievich** [comment]
Предлагаю указывать emailProtection в EKU сертификатов ФЛ и ЮП. Это разумно и соответствует уже сложившейся в ГосСУОК практике. Фактически декларируется возможность организации защищенной почты. Снимаются проблемы с тем же mime.

**Comment by agievich** [comment]
В EKU сертификатов ФЛ и ЮП добавлен флаг emailProtection
