### ISSUE TITLE
Атрибут SigningTime в SignedData

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#20]
Контейнеры SignedData, которые пересылаются в процессах (Enroll, Reneroll, Spawn, Revoke, Chpwd, Revoke), не содержат атрибут SigningTime: подписывающая сторона не фиксирует время подписи. Это разумно, поскольку у подписанта (ФЛ) может отсутствовать точный таймер. Но знать время подписи желательно во многих случаях. Например, клиент процесса может отслеживать время реакции УЦ. В бумажном документообороте время подписи обязательно.

Развилка:
1. Атрибут SigningTime никогда не включается в SignedData (как сейчас).
2. Атрибут SigningTime всегда включается в SignedData.
3. Атрибут SigningTime всегда включается в SignedData, выпущенные УЦ или агентами УЦ, и может включаться в SignedData, выпущенные другими сторонами.

**Comment by olegotory** [comment]
Как  я понимаю, когда клиент отслеживает время реакции, то он полагается только на свой таймер, т.е. ждет определенный интервал времени. Нужно ли нам соответствие стандарту на расширенные подписи? Например, РЭЦП профиля B-B ДОЛЖНА содержать следующие общие атрибуты:
– SigningTime;
– SigningCertificate.

**Comment by pavlovkv** [comment]
Я склоняюсь к первому варианту. Не считаю, что нам необходимо следовать интересам документооборота. Для подписей со временем необходимо использовать более состоятельную подпись (РЭЦП B-T и выше).

**Comment by agievich** [comment]
Компромисс: в `SignedData` _может_ включаться подписанный атрибут `SigningTime`.
