### ISSUE TITLE
Названия расширений

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#5]
В п. 8.1 заявлены следующие расширения сертификатов: SubjectKeyIdentifier, AuthorityKeyIdentifier, KeyUsage, ExtKeyUsageSyntax, certificatePolicies, BasicConstraints, SubjectAltName, CRLDistributionPoints, AuthorityInfoAccessSyntax. 

Имена расширений несколько разнородны: начинаются то с прописной буквы, то со строчной; то заканчиваются суффиксом Syntax, то не заканчиваются. Разнородность имен наследуется от СТБ 34.101.19. 

Предлагается все именовать единообразно. Для этого выполнить три замены: 
- certificatePolicies -> СertificatePolicies;
- ExtKeyUsageSyntax -> ExtKeyUsage;
- AuthorityInfoAccessSyntax -> AuthorityInfoAccess.

И еще нужно подкорректировать имена расширений в п. 8.2.2.

**Comment by pavlovkv** [comment]
Да, поддерживаю предлагаемое переименование. При написании стандарта часто возникала путаница и было много переименований туда и обратно.

**Comment by agievich** [comment]
Переименовано
