### ISSUE TITLE
Атрибуты surname и givenName нерезидентов

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#55]
Подробно описано, как должны формироваться атрибуты `surname` (фамилия) и `givenName` (имя и отчество) в сертификатах ФЛ-резидентов. Однако, ничего не сказано про сертификаты нерезидентов (согласно таблице 3, атрибуты должны присутствовать в этих сертификатах).

Каким должен быть язык атрибутов `surname` и `givenName` у нерезидентов? Нужны ли вообще эти атрибуты (имя и фамилия на английском будет в `commonName`)?

**Comment by agievich** [comment]
Продолжу описывать проблему.

В BPKI записано:
> ...фамилия (имя и отчество) задается в соответствии с удостоверением лица. записывается прописными буквами...

Для нерезидента это может означать запись иероглифами (что тогда прописные буквы?) или арабской вязью. Нужны уточнения.

**Comment by pavlovkv** [comment]
Возможно, стоит отказаться от использования` surname` и `givenName` у нерезидентов. `commonName`  должно быть достаточно.

**Comment by agievich** [comment]
1. При описании атрибутов для абстрактных ФЛ и ЮП сказано, что атрибуты формируются по удостоверениям (без слов о прописных буквах).
2. При описании атрибутов для резидентов сказано про прописные буквы.
3. При описании имени и отчества в атрибуте `givenName` резидента упомянуто, что отчества может и не быть.

Все записать в `commonName` и исключить `surname` и `givenName` --- это  не очень удачное решение, поскольку есть разные традиции объединения ФИО в единую строку (в Китае первой идет фамилия: https://en.wikipedia.org/wiki/Chinese_name).
