### ISSUE TITLE
Процесс Reenroll

### ISSUE THREAD

**Issue by NikGomel** [bcrypto/bpki#60]
7 абзац.
> Субъект сам заверяет свой запрос, подписывая его на открытом ключе действующего сертификат.

Возможно имеется ввиду на личном ключе.

**Comment by agievich** [comment]
Да, сказалось обиходное сокращение строгой фразы "подписывает на личном ключе, соответствующем открытому ключу, указанном в сертификате". 

Есть несколько мест, где нужна замена. 

**Предлагается** сократить строгую фразу до "подписывает на личном ключе сертификата". Смысл передается достаточно точно.

**Comment by agievich** [comment]
Реализовано в #61.
