### ISSUE TITLE
Версия синтаксиса в EnvelopedData

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#64]
В контейнере `EnvelopedData` используется транспорт ключа защиты. Транспорт описывается структурой `KeyTransRecipientInfo`. В этой структуре идентификатор сертификата получателя предлагается задавать через `issuerAndSerialNumber`. Но тогда согласно правилам [CMS](https://github.com/bcrypto/stb/blob/master/34.101.23/cms.md#Enveloped4) версия синтаксиса `KeyTransRecipientInfo` должна равняться 0. Соответственно версия синтаксиса `EnvelopedData` также должна равняться 0. Однако в BPKI (8.7) обе версии ошибочно равняются 2.

**Предлагается** потребовать, чтобы версии равнялись 0.

**Comment by pavlovkv** [comment]
Да, согласен. Версия `KeyTransRecipientInfo` должна быть 0 (поскольку используем `issuerAndSerialNumber`), что влечет за собой установку версии 0 в контейнере `EnvelopedData`.

**Comment by agievich** [comment]
Расследование. Не исправили версию синтаксиса после реализации https://github.com/bcrypto/bpki/issues/49.
Вопрос перенесен в #66.
