### ISSUE TITLE
пункт 8.1.3 Расширение KeyUsage

### ISSUE THREAD

**Issue by NikGomel** [bcrypto/bpki#69]
В СТБ 34.101.19 используется 9 бит для определения назначения ключа. В таблице 5 СТБ 34.101.78 только 5 бит. Не приведет ли такое разночтение к коллизиям в работе информационных систем.

**Comment by agievich** [comment]
Неиспользуемые биты (`keyAgreement`, `encipherOnly`, `decipherOnly`) должны быть нулевыми. Об этом явно не сказано в СТБ 34.101.78, хотя и подразумевалось.

Если умолчания в данном случае неочевидны, можно выпустить поправку. Хотя, как кажется, в этом нет необходимости.

**Comment by agievich** [comment]
Без реакции. Считаем, что достаточно сделанных разъяснений.
