### ISSUE TITLE
Операции с просроченными сертификатами

### ISSUE THREAD

**Issue by blackbearman** [bcrypto/bpki#70]
Возможны три состояния сертификата по отношению к сроку действия:
1. срок действия не начался;
2. сертификат действителен;
3. срок действия истек. 
Какие операции являются допустимыми в каждый момент времени?
В частности, возможен ли отзыв для сертификата с истекшим сроком действия?

**Comment by agievich** [comment]
## Q1. Можно ли отозвать сертификат с истекшим сроком действия? 

Нет, нельзя. В СОС регистрируются только неистекшие сертификаты:

> A complete CRL lists all **unexpired** certificates, within its scope, that have been revoked for one of the revocation reasons covered by the CRL scope.  A full and complete CRL lists all **unexpired** certificates issued by a CA that have been revoked for any reason. (Note that since CAs and CRL issuers are identified by name, the scope of a CRL is not affected by the key used to sign the CRL or the key(s) used to sign certificates.)

Процитирован фрагмент [RFC580](https://www.ietf.org/rfc/rfc5280.txt). См. также https://stackoverflow.com/questions/40660453/revoking-an-expired-certificate.

**Замечание**. Обратим внимание, что речь в цитате идет о полном СОС (complete CRL). В приращении СОС (delta CRL) истекшие сертификаты могут указываться, но только для того, чтобы проинформировать об их исключении из полного СОС. Причиной исключения может быть истечение срока действия отозованного сертификата (см. значение `removeFromCRL` в `CRLReason`).

## Q2. Можно ли отозвать сертификат, который еще не вступил в действие? 

Считаю, что можно. При условии следования оригинальному тексту RFC5280.

Проблема в том, что в СТБ 34.101.19 процитированный абзац RFC5280 переведен неточно -- слово "unexpired" переведено не как "неистекший", а как "действующий":

> В полном СОС регистрируются все **действующие** сертификаты, находящиеся в области его действия, причиной отзыва которых стала одна из причин, охваченных областью действия СОС. В общем и полном СОС регистрируются все выпущенные УЦ **действующие** сертификаты, которые были отозваны по любой из причин. (Следует учитывать, что вследствие того, что УЦ и эмитенты СОС идентифицируются по имени, на область действия СОС не влияет ключ, используемый для подписи СОС или ключ (и) для подписи сертификатов.)

Следует обсудить корректировку СТБ 34.101.19 (см. https://github.com/bcrypto/stb/issues/129).
