### ISSUE TITLE
Обработка поля revokePwd в формате BPKIRevokeReq

### ISSUE THREAD

**Issue by blackbearman** [bcrypto/bpki#71]
В случае, когда запрос отзыва подписан, пароль отзыва может не задаваться согласно описанию процесса Revoke. Проблема в том, что поле revokePwd не является опциональным, то есть должно задаваться всегда. 

Возможное решение: оставлять решение о проверке пароля revokePwd за УЦ, принимая во внимание, что пустая строка является допустимым значением, когда пароль отзыва не задан.

**Comment by agievich** [comment]
Предлагается изменить последнее предложение абзаца 3 п. 9.7: вместо 

> Пароль можно не задавать, если личный ключ не потерян и запрос будет подписываться.

писать

> Пароль можно не задавать, указав в `revokePwd` пустую строку, если личный ключ не потерян и запрос будет подписываться.

**Comment by agievich** [comment]
Реализовано в https://github.com/bcrypto/bpki/commit/0133570418ec1a27d452b596d9269376e0f004f9.
