### ISSUE TITLE
Требования к форматам `SignedData` и `EnvelopedData`

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bpki#77]
В пункте 5.3 Стандарта есть абзац, в котором сказано, что: 

> Форматы SignedData и EnvelopedData профилируются в 8.6, 8.7. Речь идет о профилировании в рамках ИОК. За пределами ИОК форматы SignedData и EnvelopedData могут конкретизироваться по-другому.

Эту фразу можно интерпретировать так: все подписанные (`SignedData`) и конвертованные (`EnvelopedData`) данные, которые передаются между сторонами ИОК, должны соответствовать требованиям пунктов 8.6 и 8.7 соответственно. Получается, например, подписанные данные не могут иметь базовый тип `id-data`, так как в пункте 8.6 такой тип подписываемых данных среди допустимых типов подписываемых данных не упоминается.

Возможно вместо

> ...о профилировании в рамках ИОК 

следует писать 

> ...о профилировании в рамках процессов ИОК настоящего стандарта

или что-то вроде этого.

**Comment by agievich** [comment]
Вместо

> Форматы `SignedData` и `EnvelopedData` профилируются в 8.6, 8.7. Речь идет о профилировании в рамках ИОК. За пределами ИОК форматы `SignedData` и `EnvelopedData` могут конкретизироваться по-другому.

предлагается писать

> Форматы `SignedData` и `EnvelopedData` профилируются в 8.6, 8.7. Речь идет о профилировании в рамках процессов раздела 9. Вне этих процессов форматы `SignedData` и `EnvelopedData` могут конкретизироваться по-другому.

**Comment by mkazl** [comment]
К новой формулировке тоже есть претензия: она ссылается на раздел 9, поэтому не учитывает следующие три типа подписанных данных: 

- `id-ct-TSTInfo` - ответ СШВ, который определен в разделе 8 (подпункт 8.9.2);
- `id-ct-DVCSResponseData` - ответ СШВ, который определен в разделе 8 (подпункт 8.10.2);
- `bpki-ct-resp` - ответ УЦ, который определен в разделе 8 (пункт 8.11).

**Comment by agievich** [comment]
Вторая попытка:

> Форматы `SignedData` и `EnvelopedData` профилируются в 8.6, 8.7. Профилирование касается случаев использования форматов в процессах и сервисах, определяемых или конкретизируемых в настоящем стандарте. В других случаях форматы `SignedData` и `EnvelopedData` могут профилироваться по-другому.

**Comment by mkazl** [comment]
Возможно, следует рассмотреть следующую формулировку:

> Форматы `SignedData`и `EnvelopedData`профилируются в 8.6, 8.7. Профилирование касается случаев использования форматов в процессах и сервисах касающихся операций управления РЦ и УЦ, определяемых или конкретизируемых в настоящем стандарте. Операции функционирования и управления относительно репозитария СОК и СОС в данном стандарте не рассматриваются, форматы `SignedData` и `EnvelopedData` ФЛ и ЮП могут профилироваться по-другому.

**Comment by agievich** [comment]
Предлагаемая формулировка технически неточна, ведь профилирование касается не только "операций управления РЦ и УЦ". Подготовка запроса на выпуск сертификата — это ведь не управление РЦ или УЦ. Выпуск штампа времени — это также не управление РЦ или УЦ. Можно продолжать.

Следует иметь в виду, что обсуждается формулировка из вводной части стандарта. Здесь мы не можем себе позволить  больших подробностей и "забеганий вперед". Почему выводятся из профилирования только ФЛ и ЮП? А остальные стороны? "Репозитарии СОК и СОС" в СТБ 341012.78 не упоминаются. Почему мы должны говорить о них во вводной части?  "Репозитарий" (не встречал этот термин в стандартах СТБ 34.101) или "репозиторий" (термин СТБ 34.101.19)?

**Comment by mkazl** [comment]
Предлагаем некоторое время подождать, так как возможно кем-нибудь будут предложены альтернативные формулировки. Если же таковых не будет, то можно остановиться на предложенном выше [варианте](https://github.com/bcrypto/bpki/issues/77#issuecomment-2243329836).

**Comment by agievich** [comment]
Предложенные [корректировки](https://github.com/bcrypto/bpki/issues/77#issuecomment-2243329836) реализованы в https://github.com/bcrypto/bpki/commit/788b2b0ae75bcd1e6866b1b9c94d01a9437ba01b.
