### ISSUE TITLE
Серийные номера сертификатов

### ISSUE THREAD

**Issue by agievich** [bcrypto/bpki#9]
Сторона (однозначно описывается _именем_ -- т.е. набором идентификационных атрибутов) может иметь несколько сертификатов. В частности, несколько сертификатов может быть у УЦ. 

Выпущенные УЦ сертификаты часто описываются парами (имя-УЦ, серийный-номер-сертификата). Именно такие пары предлагается использовать в SignedData для описания подписантов. 

Нельзя допустить совпадение пар или, другими словами, серийных номеров сертификатов, выпущенных одним УЦ. Даже если этот УЦ использовал при выпуске разные сертификаты. Об этом надо сказать в п. 8.3 (Сертификат открытого ключа).

**Comment by pavlovkv** [comment]
Возможно, и стоит об этом сказать, но мне кажется, что это и без этого понятно, что серийный номер уникален.

**Comment by agievich** [comment]
Добавлена фраза:
> УЦ должен гарантировать уникальность серийных номеров всех выпускаемых сертификатов, даже тех, которые подписываются на разных личных ключах УЦ.
